---
- hosts: localhost
  vars_files:
    - ../vars/common.yml
  vars:
    regular_vol_size: 50 # changed for testing
    volumes:
      - { vol_name: "{{ os_project }}-{{ win_project }}-fs01", vol_size: "{{ fs_vol_size }}", vm_name: "fs01" }
      - { vol_name: "{{ os_project }}-{{ win_project }}-fs02", vol_size: "{{ fs_vol_size }}", vm_name: "fs02" }
      - { vol_name: "{{ os_project }}-{{ win_project }}-choc", vol_size: "{{ regular_vol_size }}", vm_name: "choc" }
      - { vol_name: "{{ os_project }}-{{ win_project }}-wsus", vol_size: "{{ regular_vol_size }}", vm_name: "wsus" }
      - { vol_name: "{{ os_project }}-{{ win_project }}-File_Transfer", vol_size: "{{ regular_vol_size }}", vm_name: "fs01" }

  tasks:
  - name: Create Volumes On Openstack
    tags: teardown
    os_volume:
      display_name: "{{ item.vol_name }}"
      cloud: "{{ os_project }}"
      state: "{{ state }}"
      size: "{{ item.vol_size }}"
    loop: "{{ volumes }}"
    # option to only detach not delete???

  - name: Attach Volumes To VMs
    os_server_volume:
      cloud: "{{ os_project }}"
      state: "{{ state }}"
      server: "{{ os_project }}-{{ win_project }}-{{ item.vm_name }}"
      volume: "{{ item.vol_name }}"
    loop: "{{ volumes }}"
    # maybe dont need to run with teardown when: state == 'present'??? 

