---
# can maybe change hosts or add new metadata to non dc hosts to avoid using !meta-variant_domain_controller
- hosts: "meta-os_windows:!meta-variant_domain_controller"
  gather_facts: false
  vars_files:
    - ../vars/common.yml
    - ../vars/connection.yml
  roles:
    - role: win_domain_membership
      tags: win_domain_membership