---
- name: Check status of study
  tags: check_study
  block:
    - name: Check if study folder already exists 
      win_stat:
        path: "{{ study_folder }}"
      register: folder
      failed_when: folder.stat.exists

  rescue:
    - name: Force fail when study folder already present
      fail:
        msg="This study folder is already present"

  
