---
- name: Create Study
  tags: create_study
  block:
    - name: Create study folders and import/export folders
      win_file:
        path: "{{ study_folder }}\\{{ item }}"
        state: directory
      with_items: ["import", "export"]

    - name: Create study folders on T drive
      ansible.windows.win_file:
        path: "T:\\{{ item }}\\{{ study_code }}"
        state: directory
      with_items: ["Import", "Export"]

    - name: Create AD group
      microsoft.ad.group:
        name: "{{ study_code }}"
        description: "{{ study_code }} study"
        path: "ou=Project Groups,dc={{ win_project }},dc=loc"
        scope: domainlocal
        category: security
      delegate_to: "{{ os_project }}-{{ win_project }}-dc01"      

    - name: Create Exported AD group (Protected Only)
      microsoft.ad.group:
        name: "{{ exporter_group }}"
        description: "{{ study_code }} exporter"
        path: "ou=Project Groups,dc={{ win_project }},dc=loc"
        scope: domainlocal
        category: security
      delegate_to: "{{ os_project }}-{{ win_project }}-dc01"
      when: project_zone == 'protected'
