---
- name: Study Creation
  include_tasks: "{{ create_task }}"
  loop: [check.yml, create.yml, permissions.yml]
  loop_control:
    loop_var: create_task
  when: 
    - study_action == 'create'
    - fileserver_tasks is defined

- name: Study Deletion
  include_tasks: delete.yml
  when: 
    - study_action == 'delete'
    - fileserver_tasks is defined

- name: OS-Transfer Tasks
  include_tasks: os-transfer.yml
  when: 
    - transfer_tasks is defined 