---
- name: Clear update cache
  win_shell: |
    UsoClient RefreshSettings
    UsoClient ScanInstallWait

- name: Update Windows
  ansible.windows.win_updates:
    category_names: ["CriticalUpdates", "SecurityUpdates", "UpdateRollups"]
    skip_optional: true
    reboot: true
    reboot_timeout: 3600
  vars:
    ansible_become: true
    ansible_become_pass: "{{ ansible_password }}"
    ansible_become_user: Administrator
  ignore_errors: true

- name: Update Windows (again)
  ansible.windows.win_updates:
    category_names: '*'
    reboot: true
    reboot_timeout: 3600
  ignore_errors: true
