---
- name: Create AD user
  block:
    - name: Create user in AD
      microsoft.ad.user:
        name: "{{ username }}"
        firstname: "{{ firstname }}"
        surname: "{{ lastname }}"
        description: "Researcher - {{ study_code }}"
        path: ou=Project Users,dc={{ win_project }},dc=loc
        groups:
          add:
            - "{{ study_code }}"
            - Remote Desktop Users
        email: "{{ email }}"
        attributes:
          add:
            HomeDirectory: "{{ study_folder }}"
        password: "{{ password }}"
        password_expired: true
        state: present

    - import_tasks: exporter.yml # referece exporter so modify can be more general purpose