---
- name: Modify Export Access
  block:
    - name: Add user to exporter group 
      microsoft.ad.user:
        name: "{{ username }}"
        description: "{{ user_role }} - {{ study_code }}"
        path: ou=Project Users,dc={{ win_project }},dc=loc
        groups:
          add:
            - "{{ exporter_group }}"
        state: present
      when: user_role == 'Exporter'

    - name: Remove user from exporter group 
      microsoft.ad.user:
        name: "{{ username }}"
        description: "{{ user_role }} - {{ study_code }}"
        path: ou=Project Users,dc={{ win_project }},dc=loc
        groups:
          remove:
            - "{{ exporter_group }}"
        state: present
      when: user_role != 'Exporter'
  when: project_zone == 'protected'