- name: Install Chrony
  hosts: all-nodes
  become: yes
  vars_files:
    - ../group_vars/login.yaml
  tasks:

  - name: Install and configure Chrony
    include_tasks: ../roles/chrony/tasks/install-chrony.yaml

