- name: Install CheckMK
  hosts: all-nodes
  become: yes
  vars_files:
    - ../group_vars/login.yaml
    - ../group_vars/checkmk.yaml
    - ../passwd.yml
    - "../host_vars/{{ inventory_hostname }}.yaml"
  tasks:

  - name: Install CheckMK
    #include_tasks: ../roles/checkmk/tasks/install-checkmk.yaml
    include_tasks: ~/ansible/CheckMK/roles/install-checkmk.yaml

  - name: Add Host to CheckMK
    include_tasks: ../roles/checkmk/tasks/add-host.yaml
