- name: Bootstrap a Kubernetes Cluster Node
  hosts: all-nodes
  become: yes
  vars_files:
    - ../group_vars/login.yaml
  tasks:
  - name: Get production interface names
    shell: "ip a | grep 'master bond0' | awk '{ print $2 }' | grep en | rev | cut -c2- | rev | head -n 1"
    register: firstprodinterface

  - name: Get production interface names
    shell: "ip a | grep 'master bond0' | awk '{ print $2 }' | grep en | rev | cut -c2- | rev | tail -n 1"
    register: secondprodinterface

  - debug:
      msg: "{{ firstprodinterface.stdout }}"

  - debug:
      msg: "{{ secondprodinterface.stdout }}"
