---
- name: WSUS Features
  tags: wsus_features
  block:
    - name: Install WSUS features
      win_feature:
        name: 
          - UpdateServices-WidDB
          - UpdateServices-Services
          - UpdateServices-API
          - UpdateServices-UI
        state: present
        inlcude_management_tools: True
      register: feature_status

    - name: Rebooting Servers post feature installation
      win_reboot:
        reboot_timeout_sec: 1200
      when: feature_status.reboot_required == true

- name: WSUS Powershell
  tags: wsus_powershell
  block:
    - name: Install NuGet packageprovider (requirement for xDFS DSC module installation)
      ansible.windows.win_powershell:
        script: |
          Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

    - name: Install UpdateServices DSC module
      win_psmodule:
        name: UpdateServicesDsc
        state: Present
        accept_license: true