---
- name: Client Features
  tags: client_features
  block:
    - name: Install client features
      win_feature:
        name:
          - RDS-Connection-Broker
          - RDS-RD-Server
          - RDS-Web-Access
      register: feature_status

    - name: Install client optional features
      win_optional_feature:
        name: NetFx4
        state: present
      register: opt_feature_status

    - name: Rebooting Servers post feature installation
      win_reboot:
        reboot_timeout_sec: 1200
      when: feature_status.reboot_required == true or
            opt_feature_status.reboot_required == true

- name: Client Powershell
  tags: client_powershell
  block:
    - name: Install NuGet packageprovider (requirement for GPRegistryPolicyDsc DSC module installation)
      ansible.windows.win_powershell:
        script: |
          Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

    - name: Install GPRegistryPolicyDsc DSC module
      community.windows.win_psmodule:
        name: GPRegistryPolicyDsc
        state: Present
        accept_license: true
  when: project_zone == "standard" # possible not even needed for standard (issues getting this to work with proxy)
