choco_drive_letter: R
choco_drive_label: Chocolatey
opt_chocolatey_server_http_port: 80
opt_chocolatey_server_path: R:\tools\
choco_package_path: R:\tools\chocolatey.server\App_Data\Packages
custom_package_path: /choco/packages/custom/
community_package_path: /choco/packages/community/
local_repo_source: http://localhost/chocolatey

community_packages: 
  - vscode.install
  - vscode
  - chocolatey-windowsupdate.extension
  - KB4019990
  - KB2919442
  - KB2919355
  - KB2999226
  - KB3033929
  - KB3035131
  - firefox
  - microsoft-office-deployment
  - r.studio
  - notepadplusplus.install
  - notepadplusplus
  - wiztree
  - adobereader
  - vcredist140
  - vcredist2015
  - python312
  - DotNet4.6
  - dotnet4.7.2
  - chocolatey.server
  - chocolatey-dotnetfx.extension
  - ChocolateyGUI
  - chocolatey-core.extension
  - dotnetfx
  - Chocolatey
  - chocolatey-compatibility.extension
  - R.Project
  - veeam-agent
  - DotNet4.5.2
  - PowerBI
  - GoogleChrome
  - visualstudio2019professional
  - sql-server-2017
  - sql-server-management-studio
  - netfx-4.7.2