checkmk_server: 10.24.2.152
checkmk_agent_server: "{{ checkmk_server }}"
checkmk_agent_site: openstack
checkmk_agent_registration_site: "{{ checkmk_agent_site }}"
checkmk_agent_registration_server: "{{ checkmk_agent_server }}"
checkmk_agent_server_validate_certs: 'false'
checkmk_agent_protocol: http
checkmk_agent_user: cmkadmin
checkmk_agent_pass: "{{ checkmk_password }}"
checkmk_agent_update: 'true'
checkmk_agent_tls: 'false'
checkmk_agent_add_host: 'false'
checkmk_agent_edition: cre