---

- name: Restart squid
  ansible.builtin.service:
    name: "{{ squid_service }}"
    state: restarted

- name: "Activate Changes"
  listen: activate changes
  checkmk.general.activation:
    server_url: "{{ checkmk_agent_protocol }}://{{ checkmk_server }}:80/"
    site: "{{ checkmk_agent_site }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ checkmk_password }}"
    force_foreign_changes: "false"
    validate_certs: "false"
  run_once: true