# Setup needs re-run for some reason or it can't get the info
- name: Get facts on the interface
  setup:
    filter: ansible_{{ mgmt_interface }}
  register: interface_facts

- name: Add host to CheckMK
  checkmk.general.host:
          server_url: "{{ checkmk_server_url }}"
          site: "{{ checkmk_site }}"
          automation_user: "{{ checkmk_automation_user }}"
          automation_secret: "{{ checkmk_automation_secret }}"
          name: "{{ inventory_hostname }}"
          attributes:
            ipaddress: "{{ interface_facts.ansible_facts['ansible_' + mgmt_interface]['ipv4']['address'] }}"
          folder: "/{{ checkmk_folder }}"
          state: "present"
  delegate_to: localhost
  become: false

- name: Discover all for new host
  checkmk.general.discovery:
          server_url: "{{ checkmk_server_url }}"
          site: "{{ checkmk_site }}"
          automation_user: "{{ checkmk_automation_user }}"
          automation_secret: "{{ checkmk_automation_secret }}"
          host_name: "{{ inventory_hostname }}"
          state: "new"
  delegate_to: localhost
  become: false

- name: Run Tabula Rasa for new host
  checkmk.general.discovery:
          server_url: "{{ checkmk_server_url }}"
          site: "{{ checkmk_site }}"
          automation_user: "{{ checkmk_automation_user }}"
          automation_secret: "{{ checkmk_automation_secret }}"
          host_name: "{{ inventory_hostname }}"
          state: "tabula_rasa"
  delegate_to: localhost
  become: false

- name: Activate New Host
  checkmk.general.activation:
          server_url: "{{ checkmk_server_url }}"
          site: "{{ checkmk_site }}"
          automation_user: "{{ checkmk_automation_user }}"
          automation_secret: "{{ checkmk_automation_secret }}"
          force_foreign_changes: 'true'
  delegate_to: localhost
  become: false

- name: Register TLS
  shell: "cmk-agent-ctl register --hostname {{ inventory_hostname }} --server {{ checkmk_server_ip }} --site {{ checkmk_site }} --trust-cert --user {{ checkmk_automation_user }} --password {{ checkmk_automation_secret }}"


