- name: Updates dnf hosts
  dnf:
    name: '*'
    state: latest
    update_cache: yes
  when:
    - ansible_pkg_mgr == "dnf"

- name: Update yum hosts
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when:
    - ansible_pkg_mgr == "yum"



- name: Update apt hosts
  apt:
    name: '*'
    state: latest
    update_cache: yes
  when:
    - ansible_pkg_mgr == "apt"
