studydata_drive_letter: S
studydata_volume_label: Study_Data_DFS
archive_folder: "{{ studydata_drive_letter }}:\\Archived_Studies"
filetransfer_drive_letter: T
filetransfer_volume_label: File_Transfer

script_folder: C:\eidf
powershell_path: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
import_script: scheduled_transfer_import.ps1
export_script: scheduled_transfer_export.ps1
scheduled_task_path: \Transfer
