---
- name: Update System
  hosts: raspberry_pi
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Upgrade All Apt
      apt:
        state: latest
