---
- name: Update System
  hosts: raspberry_pi
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: true
        force_apt_get: true

    - name: Upgrade All Apt
      apt:
        state: latest
